### ISSUE TITLE
`geo_along()` error in some cases

### ISSUE THREAD

**Issue by sckott** [ropenscilabs/geoops#7]
```r
line <- '{
  "type": "Feature",
  "properties": {},
  "geometry": {
    "type": "LineString",
    "coordinates": [
      [-77.031669, 38.878605],
      [-77.029609, 38.881946],
      [-77.020339, 38.884084],
      [-77.025661, 38.885821],
      [-77.021884, 38.889563],
      [-77.019824, 38.892368]
    ]
  }
}'
geo_along(line, 1, 'kilometers')
#> [1] "{\"geometry\":{\"coordinates\":[90.99696,44.999363],\"type\":\"Point\"},\"properties\":{},\"type\":\"Feature\"}"
```

which is very very far from on the line 

kilometer value of 2 also borks, but 3 and up works, what gives?

**Comment by ateucher** [comment]
Could it be something [here](https://github.com/ropenscilabs/geoops/blob/master/src/along.cpp#L30)?

```c++
double direction = bearing(coords[i].dump(), coords[i - 1].dump()) - 180;
```

If you're in the first iteration of the loop then (i.e., on the first set of coords, so `i == 0`), then `coords[i - 1]` would be non-sensical, right?

**Comment by sckott** [comment]
good idea! will have a look

**Comment by ateucher** [comment]
Ok I think that was a wrong track...

I think the total distance along that line is less than 3 km. `geo_along` with 3 and over just returns the last point in the linestring... anything less, I think the interpolation is doing something funny - I think in `destination()`

**Comment by ateucher** [comment]
``` r
library(geoops)
point1 <- '{
"type": "Feature",
"properties": {
"marker-color": "#f00"
},
"geometry": {
"type": "Point",
"coordinates": [-77.029609, 38.881946]
}
}'
geo_destination(point1, 0.1, 90, "kilometres")
#> [1] "{\"geometry\":{\"coordinates\":[91.001271,45.0],\"type\":\"Point\"},\"properties\":{},\"type\":\"Feature\"}"
```

**Comment by ateucher** [comment]
Woot! I think I got something - in `destination` - PR imminent :)

**Comment by sckott** [comment]
awesome! thanks

**Comment by ateucher** [comment]
My first Rcpp contribution ;)
